In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_excel(r"C:\Users\Soft\Desktop\Py\Docs\dry+bean+dataset\DryBeanDataset\Dry_Bean_Dataset.xlsx")

In [3]:
df.head()

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395    610.291       208.178117       173.888747      1.197191   
1  28734    638.018       200.524796       182.734419      1.097356   
2  29380    624.110       212.826130       175.931143      1.209713   
3  30008    645.884       210.557999       182.516516      1.153638   
4  30140    620.134       201.847882       190.279279      1.060798   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1      0.411785       29172     191.272750  0.783968  0.984986   0.887034   
2      0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3      0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4      0.333680       30417     195.896503  0.773098  0.990893   0.984877   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0     0.913358      0.007332      0.003147      0.834222      0.998724  SEKER  
1     0.953861      0.006979      0.003564      0.909851      0.998430  SEKER  
2     0.908774      0.007244      0.003048      0.825871      0.999066  SEKER  
3     0.928329      0.007017      0.003215      0.861794      0.994199  SEKER  
4     0.970516      0.006697      0.003665      0.941900      0.999166  SEKER

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13611 entries, 0 to 13610
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             13611 non-null  int64  
 1   Perimeter        13611 non-null  float64
 2   MajorAxisLength  13611 non-null  float64
 3   MinorAxisLength  13611 non-null  float64
 4   AspectRation     13611 non-null  float64
 5   Eccentricity     13611 non-null  float64
 6   ConvexArea       13611 non-null  int64  
 7   EquivDiameter    13611 non-null  float64
 8   Extent           13611 non-null  float64
 9   Solidity         13611 non-null  float64
 10  roundness        13611 non-null  float64
 11  Compactness      13611 non-null  float64
 12  ShapeFactor1     13611 non-null  float64
 13  ShapeFactor2     13611 non-null  float64
 14  ShapeFactor3     13611 non-null  float64
 15  ShapeFactor4     13611 non-null  float64
 16  Class            13611 non-null  object 
dtypes: float64(1

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler = StandardScaler()

In [7]:
inp_cols = df.drop("Class", axis=1)
inp_cols

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272750  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653248  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  
0         0.913358      0.007332      0.003147      0.834222      0.998724  
1         0.953861      0.006979      0.003564      0.909851      0.998430  
2         0.908774      0.007244      0.003048      0.825871      0.999066  
3         0.928329      0.007017      0.003215      0.861794      0.994199  
4         0.970516      0.006697      0.003665      0.941900      0.999166  
...            ...           ...           ...           ...           ...  
13606     0.801865      0.006858      0.001749      0.642988      0.998385  
13607     0.822252      0.006688      0.001886      0.676099      0.998219  
13608     0.822730      0.006681      0.001888      0.676884      0.996767  
13609     0.817457      0.006724      0.001852      0.668237      0.995222  
13610     0.784997      0.007001      0.001640      0.616221      0.998180  

[13611 rows x 16 columns]

In [8]:
X = scaler.fit_transform(inp_cols)

In [9]:
X

array([[-0.84074853, -1.1433189 , -1.30659814, ...,  2.40217287,
         1.92572347,  0.83837103],
       [-0.82918764, -1.01392388, -1.39591111, ...,  3.10089314,
         2.68970162,  0.77113842],
       [-0.80715717, -1.07882906, -1.25235661, ...,  2.23509147,
         1.84135576,  0.91675514],
       ...,
       [-0.37203825, -0.44783294, -0.45047814, ...,  0.28920441,
         0.33632829,  0.39025114],
       [-0.37176543, -0.42702856, -0.42897404, ...,  0.22837538,
         0.2489734 ,  0.03644001],
       [-0.37135619, -0.38755718, -0.2917356 , ..., -0.12777587,
        -0.2764814 ,  0.71371948]])

In [10]:
pca = PCA(16)

In [11]:
pc1 = pca.fit_transform(X)

In [12]:
pc1

array([[-4.98156099e+00,  1.82469731e+00,  7.49021037e-01, ...,
        -6.16118162e-04, -2.11823131e-03, -3.97991012e-04],
       [-5.43679225e+00,  2.93236480e+00,  2.18237398e+00, ...,
         4.80626800e-03,  2.27428496e-03, -3.12223898e-03],
       [-4.75808830e+00,  1.82688385e+00,  5.14037599e-01, ...,
         9.71269698e-04, -2.48858472e-03, -2.16616900e-04],
       ...,
       [-1.41751472e+00,  1.41193703e-01, -3.87206350e-01, ...,
        -4.17719574e-04,  9.87194155e-04, -3.20956338e-04],
       [-1.11466584e+00, -2.12679323e-01,  1.44088308e-01, ...,
        -1.23647569e-03,  1.31750687e-03, -4.93277749e-04],
       [-7.66436864e-01, -6.46514107e-01, -9.94121567e-01, ...,
         8.39075166e-04, -4.81904320e-05,  7.29007389e-04]])

In [14]:
np.round(pca.explained_variance_ratio_, decimals=3)

array([0.555, 0.264, 0.08 , 0.051, 0.027, 0.011, 0.007, 0.003, 0.001,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [15]:
np.sum(np.round(pca.explained_variance_ratio_, decimals=3))

0.9990000000000001

In [16]:
np.sum([0.555, 0.264])

0.8190000000000001

In [17]:
np.sum([0.555, 0.264, 0.08 , 0.051, 0.027, 0.011])

0.9880000000000001

In [18]:
pca2 = PCA(n_components=6)

In [19]:
pc2 = pca2.fit_transform(X)

In [20]:
pc2

array([[-4.98156099,  1.82469731,  0.74902104, -0.39081166, -0.03353132,
         0.30121225],
       [-5.43679225,  2.9323648 ,  2.18237398, -0.43195954,  1.22646417,
         0.04557491],
       [-4.7580883 ,  1.82688385,  0.5140376 , -0.1258538 ,  0.13150554,
         0.2085379 ],
       ...,
       [-1.41751472,  0.1411937 , -0.38720635, -0.48643868, -0.38355528,
        -0.13733302],
       [-1.11466584, -0.21267932,  0.14408831, -0.84190323, -0.48680458,
        -0.09716026],
       [-0.76643686, -0.64651411, -0.99412157,  0.81467905,  0.25825818,
         0.05216271]])

In [21]:
np.round(pc1, decimals=2)

array([[-4.98,  1.82,  0.75, ..., -0.  , -0.  , -0.  ],
       [-5.44,  2.93,  2.18, ...,  0.  ,  0.  , -0.  ],
       [-4.76,  1.83,  0.51, ...,  0.  , -0.  , -0.  ],
       ...,
       [-1.42,  0.14, -0.39, ..., -0.  ,  0.  , -0.  ],
       [-1.11, -0.21,  0.14, ..., -0.  ,  0.  , -0.  ],
       [-0.77, -0.65, -0.99, ...,  0.  , -0.  ,  0.  ]])

In [22]:
np.round(pc2, decimals=2)

array([[-4.98,  1.82,  0.75, -0.39, -0.03,  0.3 ],
       [-5.44,  2.93,  2.18, -0.43,  1.23,  0.05],
       [-4.76,  1.83,  0.51, -0.13,  0.13,  0.21],
       ...,
       [-1.42,  0.14, -0.39, -0.49, -0.38, -0.14],
       [-1.11, -0.21,  0.14, -0.84, -0.49, -0.1 ],
       [-0.77, -0.65, -0.99,  0.81,  0.26,  0.05]])