In [12]:
import numpy as np

In [13]:
np.random.seed(0)
X = np.random.rand(100, 2)

In [14]:
X

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492],
       [0.56804456, 0.92559664],
       [0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985],
       [0.77815675, 0.87001215],
       [0.97861834, 0.79915856],
       [0.46147936, 0.78052918],
       [0.11827443, 0.63992102],
       [0.14335329, 0.94466892],
       [0.52184832, 0.41466194],
       [0.26455561, 0.77423369],
       [0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547],
       [0.66676672, 0.67063787],
       [0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077],
       [0.57019677, 0.43860151],
       [0.98837384, 0.10204481],
       [0.20887676, 0.16130952],
       [0.65310833, 0.2532916 ],
       [0.46631077, 0.24442559],
       [0.

In [15]:
mean = np.mean(X, axis=0)

In [16]:
mean

array([0.51396978, 0.48690581])

In [17]:
X_centered = X - mean

In [18]:
X_centered

array([[ 0.03484372,  0.22828355],
       [ 0.08879359,  0.05797737],
       [-0.09031498,  0.1589883 ],
       [-0.07638257,  0.40486719],
       [ 0.44969298, -0.10346429],
       [ 0.27775526,  0.04198911],
       [ 0.05407478,  0.43869082],
       [-0.44293372, -0.39977651],
       [-0.49375138,  0.34571403],
       [ 0.26418697,  0.38310633],
       [ 0.46464856,  0.31225275],
       [-0.05249042,  0.29362336],
       [-0.39569536,  0.15301521],
       [-0.37061649,  0.4577631 ],
       [ 0.00787854, -0.07224387],
       [-0.24941417,  0.28732788],
       [-0.05781945,  0.08152814],
       [-0.49517998,  0.13072968],
       [ 0.09812594,  0.13002818],
       [ 0.4297783 ,  0.19491449],
       [-0.15446188, -0.04987386],
       [ 0.18366141, -0.42668034],
       [ 0.15279693,  0.18373206],
       [-0.30358722, -0.35797952],
       [-0.19854143, -0.12319504],
       [ 0.05622699, -0.0483043 ],
       [ 0.47440406, -0.384861  ],
       [-0.30509303, -0.3255963 ],
       [ 0.13913854,

In [23]:
cov_matrix = np.cov(X_centered, rowvar=False)

In [24]:
cov_matrix

array([[ 0.08008226, -0.0055518 ],
       [-0.0055518 ,  0.08239029]])

In [25]:
eig_val, eig_vec = np.linalg.eig(cov_matrix)

In [26]:
eig_val

array([0.0755658 , 0.08690675])

In [27]:
eig_vec

array([[-0.77572974,  0.63106527],
       [-0.63106527, -0.77572974]])

In [28]:
sorted_index = np.argsort(eig_val)[::-1]

In [29]:
sorted_index

array([1, 0], dtype=int64)

In [30]:
eig_val = eig_val[sorted_index]

In [31]:
eig_val

array([0.08690675, 0.0755658 ])

In [32]:
eig_vec = eig_vec[:, sorted_index]

In [33]:
eig_vec

array([[ 0.63106527, -0.77572974],
       [-0.77572974, -0.63106527]])

In [34]:
k = 1

In [35]:
top_k_eig_vec = eig_vec[:,:k]

In [36]:
top_k_eig_vec

array([[ 0.63106527],
       [-0.77572974]])

In [37]:
pc = np.dot(X_centered, top_k_eig_vec)

In [38]:
pc

array([[-1.55097679e-01],
       [ 1.10597833e-02],
       [-1.80326601e-01],
       [-3.62269905e-01],
       [ 3.64045949e-01],
       [ 1.42709496e-01],
       [-3.06180805e-01],
       [ 3.05984435e-02],
       [-5.79770005e-01],
       [-1.30467758e-01],
       [ 5.09998218e-02],
       [-2.60897256e-01],
       [-3.68408042e-01],
       [-5.88983650e-01],
       [ 6.10135942e-02],
       [-3.80285398e-01],
       [-9.97316456e-02],
       [-4.13901790e-01],
       [-3.89428560e-02],
       [ 1.20017192e-01],
       [-5.87868918e-02],
       [ 4.46890970e-01],
       [-4.61015828e-02],
       [ 8.61120070e-02],
       [-2.97265424e-02],
       [ 7.29539816e-02],
       [ 5.97928048e-01],
       [ 6.00411187e-02],
       [ 2.69026993e-01],
       [ 1.58023174e-01],
       [ 6.80577465e-02],
       [ 3.60353025e-01],
       [-1.08615937e-01],
       [ 4.96134807e-01],
       [ 5.07610376e-01],
       [ 3.06021820e-01],
       [ 2.00562181e-01],
       [ 4.89483275e-01],
       [ 1.3

In [39]:
np.round(pc, decimals=3)

array([[-0.155],
       [ 0.011],
       [-0.18 ],
       [-0.362],
       [ 0.364],
       [ 0.143],
       [-0.306],
       [ 0.031],
       [-0.58 ],
       [-0.13 ],
       [ 0.051],
       [-0.261],
       [-0.368],
       [-0.589],
       [ 0.061],
       [-0.38 ],
       [-0.1  ],
       [-0.414],
       [-0.039],
       [ 0.12 ],
       [-0.059],
       [ 0.447],
       [-0.046],
       [ 0.086],
       [-0.03 ],
       [ 0.073],
       [ 0.598],
       [ 0.06 ],
       [ 0.269],
       [ 0.158],
       [ 0.068],
       [ 0.36 ],
       [-0.109],
       [ 0.496],
       [ 0.508],
       [ 0.306],
       [ 0.201],
       [ 0.489],
       [ 0.139],
       [ 0.148],
       [-0.067],
       [-0.443],
       [ 0.205],
       [ 0.311],
       [-0.304],
       [-0.263],
       [-0.419],
       [ 0.094],
       [ 0.408],
       [ 0.573],
       [ 0.272],
       [-0.229],
       [-0.237],
       [-0.017],
       [-0.545],
       [-0.321],
       [ 0.264],
       [ 0.259],
       [ 0.158

In [40]:
from sklearn.decomposition import PCA

In [41]:
pca = PCA(n_components=1)

In [43]:
pc_sklearn = pca.fit_transform(X)

In [44]:
pc_sklearn

array([[-1.55097679e-01],
       [ 1.10597833e-02],
       [-1.80326601e-01],
       [-3.62269905e-01],
       [ 3.64045949e-01],
       [ 1.42709496e-01],
       [-3.06180805e-01],
       [ 3.05984435e-02],
       [-5.79770005e-01],
       [-1.30467758e-01],
       [ 5.09998218e-02],
       [-2.60897256e-01],
       [-3.68408042e-01],
       [-5.88983650e-01],
       [ 6.10135942e-02],
       [-3.80285398e-01],
       [-9.97316456e-02],
       [-4.13901790e-01],
       [-3.89428560e-02],
       [ 1.20017192e-01],
       [-5.87868918e-02],
       [ 4.46890970e-01],
       [-4.61015828e-02],
       [ 8.61120070e-02],
       [-2.97265424e-02],
       [ 7.29539816e-02],
       [ 5.97928048e-01],
       [ 6.00411187e-02],
       [ 2.69026993e-01],
       [ 1.58023174e-01],
       [ 6.80577465e-02],
       [ 3.60353025e-01],
       [-1.08615937e-01],
       [ 4.96134807e-01],
       [ 5.07610376e-01],
       [ 3.06021820e-01],
       [ 2.00562181e-01],
       [ 4.89483275e-01],
       [ 1.3

In [46]:
np.round(pc_sklearn, decimals=3)

array([[-0.155],
       [ 0.011],
       [-0.18 ],
       [-0.362],
       [ 0.364],
       [ 0.143],
       [-0.306],
       [ 0.031],
       [-0.58 ],
       [-0.13 ],
       [ 0.051],
       [-0.261],
       [-0.368],
       [-0.589],
       [ 0.061],
       [-0.38 ],
       [-0.1  ],
       [-0.414],
       [-0.039],
       [ 0.12 ],
       [-0.059],
       [ 0.447],
       [-0.046],
       [ 0.086],
       [-0.03 ],
       [ 0.073],
       [ 0.598],
       [ 0.06 ],
       [ 0.269],
       [ 0.158],
       [ 0.068],
       [ 0.36 ],
       [-0.109],
       [ 0.496],
       [ 0.508],
       [ 0.306],
       [ 0.201],
       [ 0.489],
       [ 0.139],
       [ 0.148],
       [-0.067],
       [-0.443],
       [ 0.205],
       [ 0.311],
       [-0.304],
       [-0.263],
       [-0.419],
       [ 0.094],
       [ 0.408],
       [ 0.573],
       [ 0.272],
       [-0.229],
       [-0.237],
       [-0.017],
       [-0.545],
       [-0.321],
       [ 0.264],
       [ 0.259],
       [ 0.158

In [47]:
np.allclose(pc, pc_sklearn)

True

In [50]:
pca.explained_variance_

array([0.08690675])

In [51]:
pca.explained_variance_ratio_

array([0.53490112])

In [55]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [53]:
df = pd.read_excel(r"C:\Users\Soft\Desktop\Py\Docs\dry+bean+dataset\DryBeanDataset\Dry_Bean_Dataset.xlsx")

In [54]:
df.head()

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395    610.291       208.178117       173.888747      1.197191   
1  28734    638.018       200.524796       182.734419      1.097356   
2  29380    624.110       212.826130       175.931143      1.209713   
3  30008    645.884       210.557999       182.516516      1.153638   
4  30140    620.134       201.847882       190.279279      1.060798   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1      0.411785       29172     191.272750  0.783968  0.984986   0.887034   
2      0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3      0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4      0.333680       30417     195.896503  0.773098  0.990893   0.984877   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0     0.913358      0.007332      0.003147      0.834222      0.998724  SEKER  
1     0.953861      0.006979      0.003564      0.909851      0.998430  SEKER  
2     0.908774      0.007244      0.003048      0.825871      0.999066  SEKER  
3     0.928329      0.007017      0.003215      0.861794      0.994199  SEKER  
4     0.970516      0.006697      0.003665      0.941900      0.999166  SEKER

In [56]:
scaler = StandardScaler()

In [57]:
inp_cols = df.drop("Class", axis=1)
inp_cols

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272750  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653248  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  
0         0.913358      0.007332      0.003147      0.834222      0.998724  
1         0.953861      0.006979      0.003564      0.909851      0.998430  
2         0.908774      0.007244      0.003048      0.825871      0.999066  
3         0.928329      0.007017      0.003215      0.861794      0.994199  
4         0.970516      0.006697      0.003665      0.941900      0.999166  
...            ...           ...           ...           ...           ...  
13606     0.801865      0.006858      0.001749      0.642988      0.998385  
13607     0.822252      0.006688      0.001886      0.676099      0.998219  
13608     0.822730      0.006681      0.001888      0.676884      0.996767  
13609     0.817457      0.006724      0.001852      0.668237      0.995222  
13610     0.784997      0.007001      0.001640      0.616221      0.998180  

[13611 rows x 16 columns]

In [58]:
X = scaler.fit_transform(inp_cols)

In [59]:
mean2 = np.mean(X, axis=0)

In [60]:
mean2

array([ 3.34102822e-17, -1.00230847e-16, -1.33641129e-16,  3.67513104e-16,
       -4.34333668e-16, -2.27607547e-16,  1.00230847e-16, -1.33641129e-16,
       -1.99208808e-15, -2.29862741e-14,  3.34102822e-17, -1.67051411e-17,
       -1.67051411e-16,  1.33641129e-16,  7.51731349e-17,  1.96619511e-14])

In [61]:
X_centered = X - mean2

In [62]:
X_centered

array([[-0.84074853, -1.1433189 , -1.30659814, ...,  2.40217287,
         1.92572347,  0.83837103],
       [-0.82918764, -1.01392388, -1.39591111, ...,  3.10089314,
         2.68970162,  0.77113842],
       [-0.80715717, -1.07882906, -1.25235661, ...,  2.23509147,
         1.84135576,  0.91675514],
       ...,
       [-0.37203825, -0.44783294, -0.45047814, ...,  0.28920441,
         0.33632829,  0.39025114],
       [-0.37176543, -0.42702856, -0.42897404, ...,  0.22837538,
         0.2489734 ,  0.03644001],
       [-0.37135619, -0.38755718, -0.2917356 , ..., -0.12777587,
        -0.2764814 ,  0.71371948]])

In [63]:
cov_mat2 = np.cov(X_centered, rowvar=False)

In [64]:
cov_mat2

array([[ 1.00007348,  0.96679321,  0.93190206,  0.95167152,  0.24175256,
         0.26750102,  1.0000127 ,  0.98503989,  0.05434884, -0.19659898,
        -0.35755661, -0.26808652, -0.84802063, -0.63933772, -0.27216484,
        -0.35574757],
       [ 0.96679321,  1.00007348,  0.97740956,  0.91324565,  0.38530395,
         0.39109427,  0.96776031,  0.99145327, -0.02116113, -0.3039919 ,
        -0.54768691, -0.40688676, -0.86468647, -0.76764873, -0.40846531,
        -0.42934132],
       [ 0.93190206,  0.97740956,  1.00007348,  0.82611224,  0.55037521,
         0.54201145,  0.93267554,  0.96180402, -0.07806765, -0.28432317,
        -0.59640139, -0.56841883, -0.77366551, -0.85930078, -0.56822655,
        -0.48256263],
       [ 0.95167152,  0.91324565,  0.82611224,  1.00007348, -0.0091618 ,
         0.01957531,  0.95140923,  0.94860859,  0.14596778, -0.15584227,
        -0.2103594 , -0.01506758, -0.94727376, -0.47138164, -0.01932765,
        -0.26376838],
       [ 0.24175256,  0.38530395,  0

In [65]:
cov_mat2.shape

(16, 16)

In [66]:
eig_val2, eig_vec2 = np.linalg.eig(cov_mat2)

In [67]:
eig_val2

array([8.87528224e+00, 4.22926643e+00, 1.28114440e+00, 8.18312967e-01,
       4.38319068e-01, 1.83975267e-01, 1.11632319e-01, 5.20170215e-02,
       8.26086874e-03, 1.45399677e-03, 1.05426615e-03, 2.94004480e-04,
       1.48805562e-04, 1.00110039e-05, 1.78492305e-06, 2.14627105e-06])

In [68]:
eig_vec2

array([[ 2.82457959e-01,  2.45882017e-01, -6.14466784e-02,
        -3.15461943e-02, -9.13256239e-02, -3.66390031e-01,
         1.25044850e-01,  7.17479146e-02,  3.50665700e-02,
        -3.90419508e-01, -1.77686508e-01,  5.44841917e-02,
         4.62948192e-02,  6.55727932e-01,  2.31436022e-01,
         1.33190217e-01],
       [ 3.10891123e-01,  1.79302922e-01, -1.88525950e-02,
        -4.24678978e-02,  8.18198658e-02, -1.02508240e-02,
         8.15297016e-02,  3.17295057e-02, -1.57501165e-01,
         3.44383058e-01,  1.99453658e-01, -7.50549996e-01,
         3.17920227e-01,  8.13901184e-02,  1.46143883e-02,
         1.26584592e-02],
       [ 3.25823976e-01,  1.00756515e-01, -8.46919062e-02,
        -6.79308171e-03, -4.42163130e-02, -1.49091961e-02,
         1.18162545e-01, -2.00947005e-01, -3.52366424e-01,
         1.01996462e-01,  1.73639719e-01,  2.73550308e-02,
        -6.85301954e-01, -1.86251286e-01,  3.46019470e-01,
         1.74431465e-01],
       [ 2.36199383e-01,  3.43460651e

In [69]:
sorted_index = np.argsort(eig_val2)[::-1]

In [70]:
sorted_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 15, 14],
      dtype=int64)

In [71]:
eig_val2 = eig_val2[sorted_index]

In [81]:
k=6

In [82]:
top_k_eig_vec = eig_vec2[:,:k]

In [83]:
pc = np.dot(X_centered, top_k_eig_vec)

In [85]:
pc

array([[-4.98156099,  1.82469731,  0.74902104, -0.39081166, -0.03353132,
        -0.30121225],
       [-5.43679225,  2.9323648 ,  2.18237398, -0.43195954,  1.22646417,
        -0.04557491],
       [-4.7580883 ,  1.82688385,  0.5140376 , -0.1258538 ,  0.13150554,
        -0.2085379 ],
       ...,
       [-1.41751472,  0.1411937 , -0.38720635, -0.48643868, -0.38355528,
         0.13733302],
       [-1.11466584, -0.21267932,  0.14408831, -0.84190323, -0.48680458,
         0.09716026],
       [-0.76643686, -0.64651411, -0.99412157,  0.81467905,  0.25825818,
        -0.05216271]])

In [86]:
np.round(pc, decimals=2)

array([[-4.98,  1.82,  0.75, -0.39, -0.03, -0.3 ],
       [-5.44,  2.93,  2.18, -0.43,  1.23, -0.05],
       [-4.76,  1.83,  0.51, -0.13,  0.13, -0.21],
       ...,
       [-1.42,  0.14, -0.39, -0.49, -0.38,  0.14],
       [-1.11, -0.21,  0.14, -0.84, -0.49,  0.1 ],
       [-0.77, -0.65, -0.99,  0.81,  0.26, -0.05]])